logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.kry.pms: debug
server:
  address: 0.0.0.0
  port: 8060
  servlet:
    context-path: /pms-ext
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non-null
qiniu:
  oss:
    access-key: 5azdaObcIs01xmYikeM6dSPB4O32Dy97t5Z4R45K
    secret-key: Bw62mruVQ2-tamUe5YllBf9MFyO67VptKNciuNMl
    bucket: pms-oss
    path: http://pkoqxs4zt.bkt.clouddn.com
    image-host: http://oss.rooibook.com/ 

    
  
