spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non-null
  datasource:
    url: jdbc:mysql://rm-m5e00j1v2qcxae4k8do.mysql.rds.aliyuncs.com:3306/pms_temp?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong&tinyInt1isBit=false
    username: pms_root
    password: rooibook
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 1
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379